## Creating a Logistic Regression Model

### Discovery

Welcome new data analyst contractor to day 2 at Ethical Oil Inc! The humble management team were incredibly impressed with your previous efforts in creating a linear regression model to demonstrate how the close price of the S&P 500 will impact the price of oil. <br><br>
They would now like you to take this knowledge even further and would like you to understand if it's possible to predict whether the cost of oil will reach a certain threshold. Being the ever intelligent and resourceful contractor that you are, you know that you can do this with logistic regression, but have overpromised and said you will deliver them the model today, in exchange for additional paid leave. Happily, the data has already been loaded and transformed from your earlier efforts and you will just need to explore your data, build the model and analyse the results.

First we will import the required modules. They are:
- pandas
- seaborn
- statsmodels.api
- sklearn.model_selection - train_test_split
- sklearn.metrics - confusion_matrix
- matplotlib.pyplot

In [2]:
# Import required modules
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

--- 
### Data preparation
Import the stocks dataset. Set the index column as the "Date". Remember to validate the import has worked.

In [3]:
# Import the first dataset and set the date as the index
stock_df = pd.read_csv("all_stocks_5yr.csv", index_col="Date", parse_dates=True, date_format="%d%m/%Y")
stock_df.head()

                 Open      Close        Low       High
Date
01/02/2013  58.135082  58.106483  57.600095  58.656064
01/03/2013  59.430461  59.531515  58.986414  59.924352
01/04/2013  60.261989  60.294833  59.653234  60.829809
01/05/2013  63.189973  63.284582  62.681440  63.854413
01/06/2013  62.080930  61.994978  61.373427  62.672076

Import the oil dataset, set the index column as "date". Remember to validate teh import has worked.

In [4]:
# Import the second dataset and set the date as the index
oil_df = pd.read_csv("crude-oil-price.csv", index_col="date", parse_dates=True, date_format="%d%m/%Y")
oil_df.head()

            price  percentChange  change
date
01/03/1983  29.27            NaN     NaN
01/04/1983  30.63          4.646    1.36
01/05/1983  30.25         -1.241   -0.38
01/06/1983  31.38          3.736    1.13
01/07/1983  32.00          1.976    0.62

Create a new dataframe - restricting the oil data to rows (dates) that overlap between the stock and oil datasets only.

In [5]:
# Restrict the dataframe to just the dates that we want (match the stock dates)
rest_oil = oil_df.loc["01/02/2013":"01/02/2018"]
rest_oil

            price  percentChange  change
date
01/02/2013  92.05         -5.580   -5.44
01/03/2013  97.23          5.627    5.18
01/04/2013  93.46         -3.877   -3.77
01/05/2013  91.97         -1.594   -1.49
01/06/2013  96.56          4.991    4.59
...           ...            ...     ...
01/10/2017  54.38          5.245    2.71
01/11/2017  57.40          5.554    3.02
01/12/2017  60.42          5.261    3.02
01/01/2018  64.73          7.133    4.31
01/02/2018  61.64         -4.774   -3.09

[61 rows x 3 columns]

Combine the two datasets together. You should end up with 61 rows of data, and all columns, from both dataframes in the same dataframe. Use an inner join.

In [6]:
# Combine both dataframes together using an inner join. 
join_df = rest_oil.join(stock_df, how="inner")
join_df

,price,percentChange,change,Open,Close,Low,High
01/02/2013,92.05,-5.580,-5.44,58.135082,58.106483,57.600095,58.656064
01/03/2013,97.23,5.627,5.18,59.430461,59.531515,58.986414,59.924352
01/04/2013,93.46,-3.877,-3.77,60.261989,60.294833,59.653234,60.829809
01/05/2013,91.97,-1.594,-1.49,63.189973,63.284582,62.681440,63.854413
01/06/2013,96.56,4.991,4.59,62.080930,61.994978,61.373427,62.672076
...,...,...,...,...,...,...,...
01/10/2017,54.38,5.245,2.71,102.854219,102.908070,102.036919,103.656867
01/11/2017,57.40,5.554,3.02,103.862055,104.014336,103.020190,104.836911
01/12/2017,60.42,5.261,3.02,106.639923,106.488189,105.682850,107.456124
01/01/2018,64.73,7.133,4.31,111.661892,111.778353,110.634552,112.707958
01/02/2018,61.64,-4.774,-3.09,109.520721,109.226602,107.589618,111.584564

--- 
### Model planning
You will now need to understand which variables can help you determine whether we will hit the predetermined threshold or not. To begin with, we need to understand our data a little more. Lets get the mean and median oil price.

In [ ]:
#Get the mean and median prices from the dataset and print them in a single line of code.

Next we want to create a histogram to understand the distribution of price, to understand what high prices might look like. Once we have this, we can create a binary field in our dataset, showing us whether we have hit the threshold or not.

In [ ]:
# Create a historgram to determine a suitable threshold.

In [9]:
# Create a new binary column in the dataframe which will be True/False based on the threshold.

Now we can determine which variables will help us to determine if we will hit this threshold or not. We will first create a table, aggregating our dataset by our binary column. I'll use this to calculate the mean of each binary outcome.

In [10]:
# Create aggregate table on the true/false column. Find the mean value. Variables should have distinct differences in the mean.

Next create a box plot with an independent vairable and your target variable (your true/false column).

In [11]:
# Create a box plot to show the differences in distribution between your true and false groups.

Finally, a correlation matrix will help us to see if there is a strong relationship between our dependent and independent variable.

In [12]:
# Create a correlation matrix to demonstrate relationships between our variables.

---
### Building the model
Split the data into training and test datasets - include the random_state argument:<br>
random_state = 25

In [13]:
# Split the data into train and test samples

Set both the independent variable and dependent variable - remember to check they are set correctly. Don't forget to add a constant to your independent variables.

In [14]:
# Set the dependent variable and validate

In [15]:
# Set the independent variable and validate

In [16]:
# Remember to add the constant

Now generate the logistic regression model along with a summary output.

In [17]:
# Fit the model and produce the summary

--- 
### Communicating the results. 
You will now analyse the model and communicate the results. What do the following outputs tell you about the model

- Pseudo R-Squared:
- P-Value:
- Coefficient:

After this, we can generate our model predictions, and assess how accurate our model is, based on the number of correctly predicted events.

In [18]:
# Use the model to predict which dates we are likely to hit high oil prices. Chech the output.

Once we have our preductions - we can use these to create a confusion matrix, which will help us to assess the model quality.

In [19]:
# Generate a confusion matrix to test the model.

# (Optional) Generate the confusion matrix as a heatmap

# (Optional) set x and y labels, and create a title

Now we have our confusion matrix, we can asess the model quality. Our model was
- correct in __ cases 
- incorrect in __ cases

That's a great overall success rate! 
__ / __ * 100 = __ accuracy

**Basic Terminology**

**True Positives (TP)** is __: The model correctly predicted a large purchase. (Bottom right)

**True Negatives (TN)** is __: The model correctly predicted that it wont be a large purchase. (Top left)

**False Positives (FP)** is __: The model incorrectly predicted a large purchase. (Top right)

**False Negatives (FN)** is __: The model incorrectly predicted it wont be a large purchase. (Bottom left)

--- 
### Stretch goals

If you want to test your skills further, you can test the model against your test dataset, create a dataframe with the test results and produce a dataframe containing only the rows where the model has incorrectly predicted the outcome.<br><br>
What do you notice about the results?


---

In [20]:
# (Optional) Test the model on the test data


# (Optional) Produce the output and save to a dataframe column - then validate


# (Optional) Create a dataframe where only incorrect predictions are displayed

In [21]:
# (Optional) Create a confusion matrix to display test results

# (Optional) Replicate the results as a heatmap as before:

# (Optional) set x and y labels, and create a title

--- 
### Operationalise
In the real world, this is where you would draft a report, deliver briefings, implement with automation on production level servers, produce technical documentation and build this into your BAU process. This being a fictional company, the ever grateful management have granted you paid leave for all your hard work and have volunteered to take on this burden themselves. Congratulations and well done!